const express = require("express")
const userControl = require("../controllers/userController")
const authentication = require("../middleware/authentication")
const wishlistControl = require("../controllers/wishlistController")
const cartControl = require("../controllers/cartController")
const shopControl = require("../controllers/shopController")
const orderControl =require("../controllers/orderController")
const paymentControl = require("../controllers/paymentController")
const couponControl = require("../controllers/couponController")
const router = express.Router()

router.use(authentication.checkLoggedIn, authentication.checkAccountVerified)

router.get("/profile",userControl.getProfile)
router.get("/wishlist", wishlistControl.wishlist)
router.get("/cart", cartControl.getCart)
router.get("/checkout", cartControl.getCheckout)
router.get("/myOrders", shopControl.myOrders)
router.get("/myOrders/:id", shopControl.orderDetails)
router.get("/cartItemCount",cartControl.cartItemCount)
router.get("/wishlistItemCount",wishlistControl.wishlistItemCount)